capacity: 64
latent_size: 128
dilations:
  - [1, 3, 9]
  - [1, 3, 9]
  - [1, 3, 9]
  - [1, 3, 9]
strides: [2, 4, 5, 8]
lr_decay_steps: 10000
discriminator_lr: 0.001
initial_lr: 0.01
final_lr: 0.001

feature_loss_weight: 20.0
activation: snake